In [106]:

import pandas as pd
import numpy as np

data = {
    "Appointment_ID": [
        101, 102, 103, 104, 105,
        106, 107, 108, 109, 110,
        111, 112, 113, 114, 101
    ],

    "Patient_Name": [
        "Ravi Kumar", "Priya Sharma", "Arun Reddy", "Sneha Rao",
        "Kiran Das", "Meena Devi", "Vijay Kumar", "Anjali Rao",
        "Suresh Babu", "Divya Singh", "Rahul Verma", "Pooja Nair",
        "Manoj Kumar", "Lakshmi Devi", "Ravi Kumar"
    ],

    "City": [
        "Chennai", "chennai", " CHENNAI ", "Bangalore",
        "BENGALURU", None, "Hyderabad", " mumbai ",
        "MUMBAI", "Delhi", "delhi", "Hyderabad",
        "Chennai", None, "Chennai"
    ],

    "Department": [
        "Cardiology", "cardiology", " Neurology ", "Orthopedics",
        "ORTHOPEDICS", "Dermatology", "neurology", None,
        "PEDIATRICS", "Cardiology", " cardiology ", "Dermatology",
        "orthopedics", "Neurology", "Cardiology"
    ],

    "Appointment_Date": [
        "2026-01-05", "06/01/2026", "2026/01/07", "08-01-2026",
        "2026-01-09", None, "12/01/2026", "invalid_date",
        "2026/01/13", "14-01-2026", "15/01/2026",
        "2026-01-16", "17-01-2026", "2026-01-18",
        "2026-01-05"
    ],

    "Consultation_Fee": [
        "500", "600", "$450", "700", "invalid",
        "800", "550", None, "999999", "650",
        "5000", "750", "600", "700", "500"
    ],

    "Age": [
        35, 42, 28, 55, None,
        31, 47, 24, 63, 250,
        39, -5, 29, 51, 35
    ],

    "Payment_Status": [
        "Paid", "paid", " PENDING ", "Paid", "Unpaid",
        "PAID", "pending", None, "Paid", "Unpaid",
        "paid", "PENDING", "unpaid", "Paid", "Paid"
    ],

    "Notes": [
        "Regular checkup", "Follow-up", None, "Routine visit",
        "First visit", "Regular checkup", "Follow-up",
        "Urgent case", "High fee - verify", "Routine visit",
        "Follow-up", None, "Age - verify",
        "Regular checkup", "Regular checkup"
    ]
}

df = pd.DataFrame(data)

In [107]:
df

,Appointment_ID,Patient_Name,City,Department,Appointment_Date,Consultation_Fee,Age,Payment_Status,Notes
0,101,Ravi Kumar,Chennai,Cardiology,2026-01-05,500,35.0,Paid,Regular checkup
1,102,Priya Sharma,chennai,cardiology,06/01/2026,600,42.0,paid,Follow-up
2,103,Arun Reddy,CHENNAI,Neurology,2026/01/07,$450,28.0,PENDING,NaN
3,104,Sneha Rao,Bangalore,Orthopedics,08-01-2026,700,55.0,Paid,Routine visit
4,105,Kiran Das,BENGALURU,ORTHOPEDICS,2026-01-09,invalid,NaN,Unpaid,First visit
5,106,Meena Devi,NaN,Dermatology,NaN,800,31.0,PAID,Regular checkup
6,107,Vijay Kumar,Hyderabad,neurology,12/01/2026,550,47.0,pending,Follow-up
7,108,Anjali Rao,mumbai,NaN,invalid_date,NaN,24.0,NaN,Urgent case
8,109,Suresh Babu,MUMBAI,PEDIATRICS,2026/01/13,999999,63.0,Paid,High fee - verify
9,110,Divya Singh,Delhi,Cardiology,14-01-2026,650,250.0,Unpaid,Routine visit
10,111,Rahul Verma,delhi,cardiology,15/01/2026,5000,39.0,paid,Follow-up
11,112,Pooja Nair,Hyderabad,Dermatology,2026-01-16,750,-5.0,PENDING,NaN
12,113,Manoj Kumar,Chennai,orthopedics,17-01-2026,600,29.0,unpaid,Age - verify
13,114,Lakshmi Devi,NaN,Neurology,2026-01-18,700,51.0,Paid,Regular checkup
14,101,Ravi Kumar,Chennai,Cardiology,2026-01-05,500,35.0,Paid,Regular checkup

In [108]:
df.shape

(15, 9)

In [109]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Appointment_ID    15 non-null     int64
 1   Patient_Name      15 non-null     str
 2   City              13 non-null     str
 3   Department        14 non-null     str
 4   Appointment_Date  14 non-null     str
 5   Consultation_Fee  14 non-null     str
 6   Age               14 non-null     float64
 7   Payment_Status    14 non-null     str
 8   Notes             13 non-null     str
dtypes: float64(1), int64(1), str(7)
memory usage: 1.2 KB

In [110]:
df.isnull().sum()

Appointment_ID      0
Patient_Name        0
City                2
Department          1
Appointment_Date    1
Consultation_Fee    1
Age                 1
Payment_Status      1
Notes               2
dtype: int64

In [111]:
df.duplicated().sum()

np.int64(1)

In [112]:
df.describe()

       Appointment_ID         Age
count       15.000000   14.000000
mean       107.066667   51.714286
std          4.366539   59.345700
min        101.000000   -5.000000
25%        103.500000   29.500000
50%        107.000000   37.000000
75%        110.500000   50.000000
max        114.000000  250.000000

In [113]:
df_original=df.copy()

In [114]:
df_original

,Appointment_ID,Patient_Name,City,Department,Appointment_Date,Consultation_Fee,Age,Payment_Status,Notes
0,101,Ravi Kumar,Chennai,Cardiology,2026-01-05,500,35.0,Paid,Regular checkup
1,102,Priya Sharma,chennai,cardiology,06/01/2026,600,42.0,paid,Follow-up
2,103,Arun Reddy,CHENNAI,Neurology,2026/01/07,$450,28.0,PENDING,NaN
3,104,Sneha Rao,Bangalore,Orthopedics,08-01-2026,700,55.0,Paid,Routine visit
4,105,Kiran Das,BENGALURU,ORTHOPEDICS,2026-01-09,invalid,NaN,Unpaid,First visit
5,106,Meena Devi,NaN,Dermatology,NaN,800,31.0,PAID,Regular checkup
6,107,Vijay Kumar,Hyderabad,neurology,12/01/2026,550,47.0,pending,Follow-up
7,108,Anjali Rao,mumbai,NaN,invalid_date,NaN,24.0,NaN,Urgent case
8,109,Suresh Babu,MUMBAI,PEDIATRICS,2026/01/13,999999,63.0,Paid,High fee - verify
9,110,Divya Singh,Delhi,Cardiology,14-01-2026,650,250.0,Unpaid,Routine visit
10,111,Rahul Verma,delhi,cardiology,15/01/2026,5000,39.0,paid,Follow-up
11,112,Pooja Nair,Hyderabad,Dermatology,2026-01-16,750,-5.0,PENDING,NaN
12,113,Manoj Kumar,Chennai,orthopedics,17-01-2026,600,29.0,unpaid,Age - verify
13,114,Lakshmi Devi,NaN,Neurology,2026-01-18,700,51.0,Paid,Regular checkup
14,101,Ravi Kumar,Chennai,Cardiology,2026-01-05,500,35.0,Paid,Regular checkup

In [115]:
df.isna()

,Appointment_ID,Patient_Name,City,Department,Appointment_Date,Consultation_Fee,Age,Payment_Status,Notes
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False
5,False,False,True,False,True,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,True,False,True,False,True,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,True
12,False,False,False,False,False,False,False,False,False
13,False,False,True,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False

In [116]:
df.isna().sum()

Appointment_ID      0
Patient_Name        0
City                2
Department          1
Appointment_Date    1
Consultation_Fee    1
Age                 1
Payment_Status      1
Notes               2
dtype: int64

In [117]:
df[df.duplicated()]

,Appointment_ID,Patient_Name,City,Department,Appointment_Date,Consultation_Fee,Age,Payment_Status,Notes
14,101,Ravi Kumar,Chennai,Cardiology,2026-01-05,500,35.0,Paid,Regular checkup

In [118]:
df["City"] = df["City"].str.strip().str.title()
df["Department"]=df["Department"].str.strip().str.title()
df["Payment_Status"]=df["Payment_Status"].str.strip().str.title()

In [119]:
df[["Appointment_ID","City","Department","Payment_Status"]]

    Appointment_ID       City   Department Payment_Status
0              101    Chennai   Cardiology           Paid
1              102    Chennai   Cardiology           Paid
2              103    Chennai    Neurology        Pending
3              104  Bangalore  Orthopedics           Paid
4              105  Bengaluru  Orthopedics         Unpaid
5              106        NaN  Dermatology           Paid
6              107  Hyderabad    Neurology        Pending
7              108     Mumbai          NaN            NaN
8              109     Mumbai   Pediatrics           Paid
9              110      Delhi   Cardiology         Unpaid
10             111      Delhi   Cardiology           Paid
11             112  Hyderabad  Dermatology        Pending
12             113    Chennai  Orthopedics         Unpaid
13             114        NaN    Neurology           Paid
14             101    Chennai   Cardiology           Paid

In [120]:
df["City"].unique()

<StringArray>
['Chennai', 'Bangalore', 'Bengaluru', nan, 'Hyderabad', 'Mumbai', 'Delhi']
Length: 7, dtype: str

In [121]:
df["City"]=df["City"].replace({"Bengaluru":"Bangalore"})

In [122]:
df["Department"].unique()

<StringArray>
['Cardiology', 'Neurology', 'Orthopedics', 'Dermatology', nan, 'Pediatrics']
Length: 6, dtype: str

In [123]:
df["Consultation_Fee"] = (
    df["Consultation_Fee"]
    .astype("string")
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df["Consultation_Fee"] = pd.to_numeric(df["Consultation_Fee"],errors="coerce")

In [124]:
df["Consultation_Fee"].dtype

Int64Dtype()

In [125]:
df[["Appointment_ID", "Consultation_Fee"]]

    Appointment_ID  Consultation_Fee
0              101               500
1              102               600
2              103               450
3              104               700
4              105              <NA>
5              106               800
6              107               550
7              108              <NA>
8              109            999999
9              110               650
10             111              5000
11             112               750
12             113               600
13             114               700
14             101               500

In [126]:
df["Consultation_Fee"].unique()

<IntegerArray>
[500, 600, 450, 700, <NA>, 800, 550, 999999, 650, 5000, 750]
Length: 11, dtype: Int64

In [127]:
df["Appointment_Date"]=pd.to_datetime(df["Appointment_Date"],format="mixed",dayfirst=True,errors="coerce")

In [128]:
df[["Appointment_ID","Appointment_Date"]]

    Appointment_ID Appointment_Date
0              101       2026-05-01
1              102       2026-01-06
2              103       2026-07-01
3              104       2026-01-08
4              105       2026-09-01
5              106              NaT
6              107       2026-01-12
7              108              NaT
8              109       2026-01-13
9              110       2026-01-14
10             111       2026-01-15
11             112       2026-01-16
12             113       2026-01-17
13             114       2026-01-18
14             101       2026-05-01

In [129]:
df["Appointment_Date"].dtype

dtype('<M8[us]')

In [130]:
df

,Appointment_ID,Patient_Name,City,Department,Appointment_Date,Consultation_Fee,Age,Payment_Status,Notes
0,101,Ravi Kumar,Chennai,Cardiology,2026-05-01,500,35.0,Paid,Regular checkup
1,102,Priya Sharma,Chennai,Cardiology,2026-01-06,600,42.0,Paid,Follow-up
2,103,Arun Reddy,Chennai,Neurology,2026-07-01,450,28.0,Pending,NaN
3,104,Sneha Rao,Bangalore,Orthopedics,2026-01-08,700,55.0,Paid,Routine visit
4,105,Kiran Das,Bangalore,Orthopedics,2026-09-01,<NA>,NaN,Unpaid,First visit
5,106,Meena Devi,NaN,Dermatology,NaT,800,31.0,Paid,Regular checkup
6,107,Vijay Kumar,Hyderabad,Neurology,2026-01-12,550,47.0,Pending,Follow-up
7,108,Anjali Rao,Mumbai,NaN,NaT,<NA>,24.0,NaN,Urgent case
8,109,Suresh Babu,Mumbai,Pediatrics,2026-01-13,999999,63.0,Paid,High fee - verify
9,110,Divya Singh,Delhi,Cardiology,2026-01-14,650,250.0,Unpaid,Routine visit
10,111,Rahul Verma,Delhi,Cardiology,2026-01-15,5000,39.0,Paid,Follow-up
11,112,Pooja Nair,Hyderabad,Dermatology,2026-01-16,750,-5.0,Pending,NaN
12,113,Manoj Kumar,Chennai,Orthopedics,2026-01-17,600,29.0,Unpaid,Age - verify
13,114,Lakshmi Devi,NaN,Neurology,2026-01-18,700,51.0,Paid,Regular checkup
14,101,Ravi Kumar,Chennai,Cardiology,2026-05-01,500,35.0,Paid,Regular checkup

In [131]:
df_original

,Appointment_ID,Patient_Name,City,Department,Appointment_Date,Consultation_Fee,Age,Payment_Status,Notes
0,101,Ravi Kumar,Chennai,Cardiology,2026-01-05,500,35.0,Paid,Regular checkup
1,102,Priya Sharma,chennai,cardiology,06/01/2026,600,42.0,paid,Follow-up
2,103,Arun Reddy,CHENNAI,Neurology,2026/01/07,$450,28.0,PENDING,NaN
3,104,Sneha Rao,Bangalore,Orthopedics,08-01-2026,700,55.0,Paid,Routine visit
4,105,Kiran Das,BENGALURU,ORTHOPEDICS,2026-01-09,invalid,NaN,Unpaid,First visit
5,106,Meena Devi,NaN,Dermatology,NaN,800,31.0,PAID,Regular checkup
6,107,Vijay Kumar,Hyderabad,neurology,12/01/2026,550,47.0,pending,Follow-up
7,108,Anjali Rao,mumbai,NaN,invalid_date,NaN,24.0,NaN,Urgent case
8,109,Suresh Babu,MUMBAI,PEDIATRICS,2026/01/13,999999,63.0,Paid,High fee - verify
9,110,Divya Singh,Delhi,Cardiology,14-01-2026,650,250.0,Unpaid,Routine visit
10,111,Rahul Verma,delhi,cardiology,15/01/2026,5000,39.0,paid,Follow-up
11,112,Pooja Nair,Hyderabad,Dermatology,2026-01-16,750,-5.0,PENDING,NaN
12,113,Manoj Kumar,Chennai,orthopedics,17-01-2026,600,29.0,unpaid,Age - verify
13,114,Lakshmi Devi,NaN,Neurology,2026-01-18,700,51.0,Paid,Regular checkup
14,101,Ravi Kumar,Chennai,Cardiology,2026-01-05,500,35.0,Paid,Regular checkup

In [132]:
df.describe()

,Appointment_ID,Appointment_Date,Consultation_Fee,Age
count,15.000000,13,13.0,14.000000
mean,107.066667,2026-03-01 12:55:23.076923,77830.692308,51.714286
min,101.000000,2026-01-06 00:00:00,450.0,-5.000000
25%,103.500000,2026-01-13 00:00:00,550.0,29.500000
50%,107.000000,2026-01-16 00:00:00,650.0,37.000000
75%,110.500000,2026-05-01 00:00:00,750.0,50.000000
max,114.000000,2026-09-01 00:00:00,999999.0,250.000000
std,4.366539,NaN,277079.758877,59.345700

In [133]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Appointment_ID    15 non-null     int64
 1   Patient_Name      15 non-null     str
 2   City              13 non-null     str
 3   Department        14 non-null     str
 4   Appointment_Date  13 non-null     datetime64[us]
 5   Consultation_Fee  13 non-null     Int64
 6   Age               14 non-null     float64
 7   Payment_Status    14 non-null     str
 8   Notes             13 non-null     str
dtypes: Int64(1), datetime64[us](1), float64(1), int64(1), str(5)
memory usage: 1.2 KB

In [134]:
df.isna().sum()

Appointment_ID      0
Patient_Name        0
City                2
Department          1
Appointment_Date    2
Consultation_Fee    2
Age                 1
Payment_Status      1
Notes               2
dtype: int64

In [135]:
df.loc[
    (df["Age"] < 0) | (df["Age"] > 120),
    "Age"
] = np.nan

In [136]:
df.isna().sum()

Appointment_ID      0
Patient_Name        0
City                2
Department          1
Appointment_Date    2
Consultation_Fee    2
Age                 3
Payment_Status      1
Notes               2
dtype: int64

In [137]:
df=df.drop_duplicates()

In [138]:
df[df.duplicated()]

Empty DataFrame
Columns: [Appointment_ID, Patient_Name, City, Department, Appointment_Date, Consultation_Fee, Age, Payment_Status, Notes]
Index: []

In [139]:
Q1 = df["Consultation_Fee"].quantile(0.25)
Q3 = df["Consultation_Fee"].quantile(0.75)

IQR = Q3 - Q1

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

Q1: 587.5
Q3: 762.5
IQR: 175.0

In [140]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

Lower bound: 325.0
Upper bound: 1025.0

In [141]:
fee_outliers=df[(df["Consultation_Fee"]<lower_bound)|(df["Consultation_Fee"]>upper_bound)]

In [142]:
fee_outliers[["Appointment_ID","Consultation_Fee"]]

    Appointment_ID  Consultation_Fee
8              109            999999
10             111              5000

In [156]:
df.loc[df["City"].isna(),"City"]="Unknown"
df.loc[df["Department"].isna(),"Department"]="Unknown"
df.loc[df["Notes"].isna(),"Notes"]="Unknown"
df.loc[df["Payment_Status"].isna(),"Payment_Status"]="Unknown"

In [157]:
df

,Appointment_ID,Patient_Name,City,Department,Appointment_Date,Consultation_Fee,Age,Payment_Status,Notes
0,101,Ravi Kumar,Chennai,Cardiology,2026-05-01,500,35.0,Paid,Regular checkup
1,102,Priya Sharma,Chennai,Cardiology,2026-01-06,600,42.0,Paid,Follow-up
2,103,Arun Reddy,Chennai,Neurology,2026-07-01,450,28.0,Pending,Unknown
3,104,Sneha Rao,Bangalore,Orthopedics,2026-01-08,700,55.0,Paid,Routine visit
4,105,Kiran Das,Bangalore,Orthopedics,2026-09-01,<NA>,35.0,Unpaid,First visit
5,106,Meena Devi,Unknown,Dermatology,NaT,800,31.0,Paid,Regular checkup
6,107,Vijay Kumar,Hyderabad,Neurology,2026-01-12,550,47.0,Pending,Follow-up
7,108,Anjali Rao,Mumbai,Unknown,NaT,<NA>,24.0,Unknown,Urgent case
9,110,Divya Singh,Delhi,Cardiology,2026-01-14,650,35.0,Unpaid,Routine visit
11,112,Pooja Nair,Hyderabad,Dermatology,2026-01-16,750,35.0,Pending,Unknown
12,113,Manoj Kumar,Chennai,Orthopedics,2026-01-17,600,29.0,Unpaid,Age - verify
13,114,Lakshmi Devi,Unknown,Neurology,2026-01-18,700,51.0,Paid,Regular checkup

In [158]:
df=df[((df["Consultation_Fee"]>=lower_bound)&(df["Consultation_Fee"]<=upper_bound))|df["Consultation_Fee"].isna()]

In [159]:
df

,Appointment_ID,Patient_Name,City,Department,Appointment_Date,Consultation_Fee,Age,Payment_Status,Notes
0,101,Ravi Kumar,Chennai,Cardiology,2026-05-01,500,35.0,Paid,Regular checkup
1,102,Priya Sharma,Chennai,Cardiology,2026-01-06,600,42.0,Paid,Follow-up
2,103,Arun Reddy,Chennai,Neurology,2026-07-01,450,28.0,Pending,Unknown
3,104,Sneha Rao,Bangalore,Orthopedics,2026-01-08,700,55.0,Paid,Routine visit
4,105,Kiran Das,Bangalore,Orthopedics,2026-09-01,<NA>,35.0,Unpaid,First visit
5,106,Meena Devi,Unknown,Dermatology,NaT,800,31.0,Paid,Regular checkup
6,107,Vijay Kumar,Hyderabad,Neurology,2026-01-12,550,47.0,Pending,Follow-up
7,108,Anjali Rao,Mumbai,Unknown,NaT,<NA>,24.0,Unknown,Urgent case
9,110,Divya Singh,Delhi,Cardiology,2026-01-14,650,35.0,Unpaid,Routine visit
11,112,Pooja Nair,Hyderabad,Dermatology,2026-01-16,750,35.0,Pending,Unknown
12,113,Manoj Kumar,Chennai,Orthopedics,2026-01-17,600,29.0,Unpaid,Age - verify
13,114,Lakshmi Devi,Unknown,Neurology,2026-01-18,700,51.0,Paid,Regular checkup

In [160]:
df

,Appointment_ID,Patient_Name,City,Department,Appointment_Date,Consultation_Fee,Age,Payment_Status,Notes
0,101,Ravi Kumar,Chennai,Cardiology,2026-05-01,500,35.0,Paid,Regular checkup
1,102,Priya Sharma,Chennai,Cardiology,2026-01-06,600,42.0,Paid,Follow-up
2,103,Arun Reddy,Chennai,Neurology,2026-07-01,450,28.0,Pending,Unknown
3,104,Sneha Rao,Bangalore,Orthopedics,2026-01-08,700,55.0,Paid,Routine visit
4,105,Kiran Das,Bangalore,Orthopedics,2026-09-01,<NA>,35.0,Unpaid,First visit
5,106,Meena Devi,Unknown,Dermatology,NaT,800,31.0,Paid,Regular checkup
6,107,Vijay Kumar,Hyderabad,Neurology,2026-01-12,550,47.0,Pending,Follow-up
7,108,Anjali Rao,Mumbai,Unknown,NaT,<NA>,24.0,Unknown,Urgent case
9,110,Divya Singh,Delhi,Cardiology,2026-01-14,650,35.0,Unpaid,Routine visit
11,112,Pooja Nair,Hyderabad,Dermatology,2026-01-16,750,35.0,Pending,Unknown
12,113,Manoj Kumar,Chennai,Orthopedics,2026-01-17,600,29.0,Unpaid,Age - verify
13,114,Lakshmi Devi,Unknown,Neurology,2026-01-18,700,51.0,Paid,Regular checkup

In [161]:
mean_age = df["Age"].mean()
median_age = df["Age"].median()

print("Mean age:", mean_age)
print("Median age:", median_age)

Mean age: 37.25
Median age: 35.0

In [162]:
mean_age=round(mean_age)
median_age=round(median_age)

In [163]:
print("Mean age:", mean_age)
print("Median age:", median_age)

Mean age: 37
Median age: 35

In [164]:
df["Age"] = df["Age"].fillna(median_age)

In [165]:
df

,Appointment_ID,Patient_Name,City,Department,Appointment_Date,Consultation_Fee,Age,Payment_Status,Notes
0,101,Ravi Kumar,Chennai,Cardiology,2026-05-01,500,35.0,Paid,Regular checkup
1,102,Priya Sharma,Chennai,Cardiology,2026-01-06,600,42.0,Paid,Follow-up
2,103,Arun Reddy,Chennai,Neurology,2026-07-01,450,28.0,Pending,Unknown
3,104,Sneha Rao,Bangalore,Orthopedics,2026-01-08,700,55.0,Paid,Routine visit
4,105,Kiran Das,Bangalore,Orthopedics,2026-09-01,<NA>,35.0,Unpaid,First visit
5,106,Meena Devi,Unknown,Dermatology,NaT,800,31.0,Paid,Regular checkup
6,107,Vijay Kumar,Hyderabad,Neurology,2026-01-12,550,47.0,Pending,Follow-up
7,108,Anjali Rao,Mumbai,Unknown,NaT,<NA>,24.0,Unknown,Urgent case
9,110,Divya Singh,Delhi,Cardiology,2026-01-14,650,35.0,Unpaid,Routine visit
11,112,Pooja Nair,Hyderabad,Dermatology,2026-01-16,750,35.0,Pending,Unknown
12,113,Manoj Kumar,Chennai,Orthopedics,2026-01-17,600,29.0,Unpaid,Age - verify
13,114,Lakshmi Devi,Unknown,Neurology,2026-01-18,700,51.0,Paid,Regular checkup

In [166]:
df.isna().sum()

Appointment_ID      0
Patient_Name        0
City                0
Department          0
Appointment_Date    2
Consultation_Fee    2
Age                 0
Payment_Status      0
Notes               0
dtype: int64

In [167]:
df

,Appointment_ID,Patient_Name,City,Department,Appointment_Date,Consultation_Fee,Age,Payment_Status,Notes
0,101,Ravi Kumar,Chennai,Cardiology,2026-05-01,500,35.0,Paid,Regular checkup
1,102,Priya Sharma,Chennai,Cardiology,2026-01-06,600,42.0,Paid,Follow-up
2,103,Arun Reddy,Chennai,Neurology,2026-07-01,450,28.0,Pending,Unknown
3,104,Sneha Rao,Bangalore,Orthopedics,2026-01-08,700,55.0,Paid,Routine visit
4,105,Kiran Das,Bangalore,Orthopedics,2026-09-01,<NA>,35.0,Unpaid,First visit
5,106,Meena Devi,Unknown,Dermatology,NaT,800,31.0,Paid,Regular checkup
6,107,Vijay Kumar,Hyderabad,Neurology,2026-01-12,550,47.0,Pending,Follow-up
7,108,Anjali Rao,Mumbai,Unknown,NaT,<NA>,24.0,Unknown,Urgent case
9,110,Divya Singh,Delhi,Cardiology,2026-01-14,650,35.0,Unpaid,Routine visit
11,112,Pooja Nair,Hyderabad,Dermatology,2026-01-16,750,35.0,Pending,Unknown
12,113,Manoj Kumar,Chennai,Orthopedics,2026-01-17,600,29.0,Unpaid,Age - verify
13,114,Lakshmi Devi,Unknown,Neurology,2026-01-18,700,51.0,Paid,Regular checkup

In [171]:
df["Date_Was_Missing"] = df["Appointment_Date"].isna().astype(int)
df["Fee_Was_Missing"] = df["Consultation_Fee"].isna().astype(int)

In [172]:
df

,Appointment_ID,Patient_Name,City,Department,Appointment_Date,Consultation_Fee,Age,Payment_Status,Notes,Date_Was_Missing,Fee_Was_Missing
0,101,Ravi Kumar,Chennai,Cardiology,2026-05-01,500,35.0,Paid,Regular checkup,0,0
1,102,Priya Sharma,Chennai,Cardiology,2026-01-06,600,42.0,Paid,Follow-up,0,0
2,103,Arun Reddy,Chennai,Neurology,2026-07-01,450,28.0,Pending,Unknown,0,0
3,104,Sneha Rao,Bangalore,Orthopedics,2026-01-08,700,55.0,Paid,Routine visit,0,0
4,105,Kiran Das,Bangalore,Orthopedics,2026-09-01,<NA>,35.0,Unpaid,First visit,0,1
5,106,Meena Devi,Unknown,Dermatology,NaT,800,31.0,Paid,Regular checkup,1,0
6,107,Vijay Kumar,Hyderabad,Neurology,2026-01-12,550,47.0,Pending,Follow-up,0,0
7,108,Anjali Rao,Mumbai,Unknown,NaT,<NA>,24.0,Unknown,Urgent case,1,1
9,110,Divya Singh,Delhi,Cardiology,2026-01-14,650,35.0,Unpaid,Routine visit,0,0
11,112,Pooja Nair,Hyderabad,Dermatology,2026-01-16,750,35.0,Pending,Unknown,0,0
12,113,Manoj Kumar,Chennai,Orthopedics,2026-01-17,600,29.0,Unpaid,Age - verify,0,0
13,114,Lakshmi Devi,Unknown,Neurology,2026-01-18,700,51.0,Paid,Regular checkup,0,0

In [173]:
df.isna().sum()

Appointment_ID      0
Patient_Name        0
City                0
Department          0
Appointment_Date    2
Consultation_Fee    2
Age                 0
Payment_Status      0
Notes               0
Date_Was_Missing    0
Fee_Was_Missing     0
dtype: int64