In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
print("Numpy Version:",np.__version__)
print("Pandas Version:",pd.__version__)

Numpy Version: 2.4.6
Pandas Version: 3.1.0

In [6]:
df=pd.read_csv('it_support.csv')

In [7]:
df

,Ticket_ID,Category,Priority,Resolution_Hours,Affected_Users,SLA_Breached
0,T101,Network,High,8,25,Yes
1,T102,Software,Medium,4,5,No
2,T103,Hardware,High,10,12,Yes
3,T104,Network,Low,2,3,No
4,T105,Software,High,7,18,Yes
5,T106,Database,Critical,12,40,Yes
6,T107,Hardware,Medium,5,6,No
7,T108,Network,Critical,15,50,Yes
8,T109,Software,Low,1,2,No
9,T110,Database,High,9,20,Yes
10,T111,Hardware,Low,3,4,No
11,T112,Network,Medium,6,10,No
12,T113,Database,Medium,5,8,No
13,T114,Software,Critical,14,35,Yes
14,T115,Hardware,High,8,15,Yes

In [8]:
df.head()

  Ticket_ID  Category Priority  Resolution_Hours  Affected_Users SLA_Breached
0      T101   Network     High                 8              25          Yes
1      T102  Software   Medium                 4               5           No
2      T103  Hardware     High                10              12          Yes
3      T104   Network      Low                 2               3           No
4      T105  Software     High                 7              18          Yes

In [9]:
df.head(2)

  Ticket_ID  Category Priority  Resolution_Hours  Affected_Users SLA_Breached
0      T101   Network     High                 8              25          Yes
1      T102  Software   Medium                 4               5           No

In [10]:
df.tail(3)

,Ticket_ID,Category,Priority,Resolution_Hours,Affected_Users,SLA_Breached
12,T113,Database,Medium,5,8,No
13,T114,Software,Critical,14,35,Yes
14,T115,Hardware,High,8,15,Yes

In [11]:
df.shape

(15, 6)

In [12]:
df.columns

Index(['Ticket_ID', 'Category', 'Priority', 'Resolution_Hours',
       'Affected_Users', 'SLA_Breached'],
      dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Ticket_ID         15 non-null     str
 1   Category          15 non-null     str
 2   Priority          15 non-null     str
 3   Resolution_Hours  15 non-null     int64
 4   Affected_Users    15 non-null     int64
 5   SLA_Breached      15 non-null     str
dtypes: int64(2), str(4)
memory usage: 852.0 bytes

In [14]:
df.nunique()

Ticket_ID           15
Category             4
Priority             4
Resolution_Hours    13
Affected_Users      15
SLA_Breached         2
dtype: int64

In [15]:
df.describe()

       Resolution_Hours  Affected_Users
count         15.000000       15.000000
mean           7.266667       16.866667
std            4.199773       14.710864
min            1.000000        2.000000
25%            4.500000        5.500000
50%            7.000000       12.000000
75%            9.500000       22.500000
max           15.000000       50.000000

In [16]:
df.describe(include="all")

,Ticket_ID,Category,Priority,Resolution_Hours,Affected_Users,SLA_Breached
count,15,15,15,15.000000,15.000000,15
unique,15,4,4,NaN,NaN,2
top,T101,Network,High,NaN,NaN,Yes
freq,1,4,5,NaN,NaN,8
mean,NaN,NaN,NaN,7.266667,16.866667,NaN
std,NaN,NaN,NaN,4.199773,14.710864,NaN
min,NaN,NaN,NaN,1.000000,2.000000,NaN
25%,NaN,NaN,NaN,4.500000,5.500000,NaN
50%,NaN,NaN,NaN,7.000000,12.000000,NaN
75%,NaN,NaN,NaN,9.500000,22.500000,NaN
max,NaN,NaN,NaN,15.000000,50.000000,NaN

In [17]:
df.isnull()

,Ticket_ID,Category,Priority,Resolution_Hours,Affected_Users,SLA_Breached
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False

In [18]:
df.isnull().sum()

Ticket_ID           0
Category            0
Priority            0
Resolution_Hours    0
Affected_Users      0
SLA_Breached        0
dtype: int64

In [19]:
df.isnull().count()

Ticket_ID           15
Category            15
Priority            15
Resolution_Hours    15
Affected_Users      15
SLA_Breached        15
dtype: int64

In [20]:
df.notnull().sum()

Ticket_ID           15
Category            15
Priority            15
Resolution_Hours    15
Affected_Users      15
SLA_Breached        15
dtype: int64

In [21]:
df.count()

Ticket_ID           15
Category            15
Priority            15
Resolution_Hours    15
Affected_Users      15
SLA_Breached        15
dtype: int64

In [22]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df["Resolution_Cost"]=df["Resolution_Hours"]*500

In [38]:
df[["Ticket_ID","Resolution_Hours","Resolution_Cost"]]

   Ticket_ID  Resolution_Hours  Resolution_Cost
0       T101                 8             4000
1       T102                 4             2000
2       T103                10             5000
3       T104                 2             1000
4       T105                 7             3500
5       T106                12             6000
6       T107                 5             2500
7       T108                15             7500
8       T109                 1              500
9       T110                 9             4500
10      T111                 3             1500
11      T112                 6             3000
12      T113                 5             2500
13      T114                14             7000
14      T115                 8             4000

In [27]:
df.to_csv("it_support.csv",index=False)

In [28]:
df[df["Resolution_Hours"]>10]

,Ticket_ID,Category,Priority,Resolution_Hours,Affected_Users,SLA_Breached,Resolution_Cost
5,T106,Database,Critical,12,40,Yes,6000
7,T108,Network,Critical,15,50,Yes,7500
13,T114,Software,Critical,14,35,Yes,7000

In [35]:
df[df["SLA_Breached"]=="Yes"]

,Ticket_ID,Category,Priority,Resolution_Hours,Affected_Users,SLA_Breached,Resolution_Cost
0,T101,Network,High,8,25,Yes,4000
2,T103,Hardware,High,10,12,Yes,5000
4,T105,Software,High,7,18,Yes,3500
5,T106,Database,Critical,12,40,Yes,6000
7,T108,Network,Critical,15,50,Yes,7500
9,T110,Database,High,9,20,Yes,4500
13,T114,Software,Critical,14,35,Yes,7000
14,T115,Hardware,High,8,15,Yes,4000

In [36]:
df[(df["SLA_Breached"]=="Yes")&(df["Resolution_Cost"]>5000)]

,Ticket_ID,Category,Priority,Resolution_Hours,Affected_Users,SLA_Breached,Resolution_Cost
5,T106,Database,Critical,12,40,Yes,6000
7,T108,Network,Critical,15,50,Yes,7500
13,T114,Software,Critical,14,35,Yes,7000

In [41]:
df.groupby("Category")["Resolution_Cost"].sum()

Category
Database    13000
Hardware    13000
Network     15500
Software    13000
Name: Resolution_Cost, dtype: int64

In [43]:
print(df["Resolution_Cost"].sum())

54500

In [44]:
resolution_hours=df["Resolution_Hours"].to_numpy()

In [45]:
resolution_hours

array([ 8,  4, 10,  2,  7, 12,  5, 15,  1,  9,  3,  6,  5, 14,  8])

In [47]:
type(resolution_hours)

numpy.ndarray

In [48]:
resolution_hours.shape

(15,)

In [49]:
resolution_hours.ndim

1

In [59]:
print("Total Resolution Hours:",np.sum(resolution_hours))
print("Maximum Resolution Hours:",np.max(resolution_hours))
print("Minimum Resolution Hours:",np.min(resolution_hours))
print("Mean Resolution Hours:",np.mean(resolution_hours))

Total Resolution Hours: 109
Maximum Resolution Hours: 15
Minimum Resolution Hours: 1
Mean Resolution Hours: 7.266666666666667

In [60]:
incr_res_hours=resolution_hours*1.01

In [61]:
print(incr_res_hours)

[ 8.08  4.04 10.1   2.02  7.07 12.12  5.05 15.15  1.01  9.09  3.03  6.06
  5.05 14.14  8.08]

In [63]:
print(resolution_hours[resolution_hours>10])

[12 15 14]